// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-oaXcudLqOWKjXsG-PBwhJMMbQOZubis',
    appId: '1:926112065238:web:6f9443ea412a3d278e8b77',
    messagingSenderId: '926112065238',
    projectId: 'familysafetyapp-af7cc',
    authDomain: 'familysafetyapp-af7cc.firebaseapp.com',
    storageBucket: 'familysafetyapp-af7cc.firebasestorage.app',
    measurementId: 'G-6EH1QKBBCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRODE0rlMythg9JW71u4HFi_o45FY0ngk',
    appId: '1:926112065238:android:84967bf21e9da2b58e8b77',
    messagingSenderId: '926112065238',
    projectId: 'familysafetyapp-af7cc',
    storageBucket: 'familysafetyapp-af7cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bG-7g1M22jLWwXAuGStbg66YXMAg-gM',
    appId: '1:926112065238:ios:fbeaae4b15b7e50f8e8b77',
    messagingSenderId: '926112065238',
    projectId: 'familysafetyapp-af7cc',
    storageBucket: 'familysafetyapp-af7cc.firebasestorage.app',
    androidClientId: '926112065238-5f7835s0nr5e4hl5qbcjo6tmdo5n7s8k.apps.googleusercontent.com',
    iosClientId: '926112065238-mtc3ss0cfcnj4rtri4r0qrgrf68hjik1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8bG-7g1M22jLWwXAuGStbg66YXMAg-gM',
    appId: '1:926112065238:ios:fbeaae4b15b7e50f8e8b77',
    messagingSenderId: '926112065238',
    projectId: 'familysafetyapp-af7cc',
    storageBucket: 'familysafetyapp-af7cc.firebasestorage.app',
    androidClientId: '926112065238-5f7835s0nr5e4hl5qbcjo6tmdo5n7s8k.apps.googleusercontent.com',
    iosClientId: '926112065238-mtc3ss0cfcnj4rtri4r0qrgrf68hjik1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-oaXcudLqOWKjXsG-PBwhJMMbQOZubis',
    appId: '1:926112065238:web:dd51536a864dfd888e8b77',
    messagingSenderId: '926112065238',
    projectId: 'familysafetyapp-af7cc',
    authDomain: 'familysafetyapp-af7cc.firebaseapp.com',
    storageBucket: 'familysafetyapp-af7cc.firebasestorage.app',
    measurementId: 'G-CCQTCMT69V',
  );
}
